name: Build, check formatting and test
run-name: ${{ github.actor }} pipeline
on: [push]
jobs:
  TestJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.1
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Check pre-commit
        run: |
          pre-commit run --all-files

      # - name: Lint with flake8
      #   run: |
      #     # stop the build if there are Python syntax errors or undefined names
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
